[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [{ name = "Lucas de Freitas Pereira" }]
name = "dune_evolution_tools"
version = "0.1.5"
description = "Fast dune toe storm erosion model (Larson 2004 + Larson 2016) with Numba RK4 core"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy", "matplotlib"]

[tool.setuptools.packages.find]
where = ["."]
include = ["dune_evolution_tools*"]
